import pyautogui as mario
# mario.mouseInfo()
mario.press ("Win")
mario.sleep(2)
mario.write ("Instagram")
mario.sleep(3)
mario.press("Enter")
mario.sleep(1)
mario.click(442,392)
mario.sleep(5)
mario.moveTo(442,392)
mario.click()
mario.write("ricardo da massa")
mario.sleep(1)
mario.press("Tab")
mario.write("12334545667")
mario.press("Enter")
